# Generated by Django 5.0.6 on 2026-01-16 03:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_productprice_amount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakEvenAnalysisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la configuración', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Configuración activa')),
                ('import_admin_cost_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), help_text='Tasa de costos administrativos de importación (default: 0.20 = 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('iva_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1600'), help_text='Tasa de IVA (default: 0.16 = 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('vat_retention_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0800'), help_text='Tasa de retención de IVA (default: 0.08 = 8%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('isr_retention_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0250'), help_text='Tasa de retención ISR (default: 0.025 = 2.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('marketplace_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1500'), help_text='Tasa de comisión del marketplace (default: 0.15 = 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('fixed_shipping_min_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('fixed_shipping_min', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('70.00'), default_currency='MXN', help_text='Costo mínimo de envío en MXN', max_digits=10)),
                ('fixed_shipping_max_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3)),
                ('fixed_shipping_max', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('100.00'), default_currency='MXN', help_text='Costo máximo de envío en MXN', max_digits=10)),
                ('min_profit_margin', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='Margen mínimo de ganancia (default: 0.10 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('target_profit_margin', models.DecimalField(decimal_places=4, default=Decimal('0.2500'), help_text='Margen objetivo de ganancia (default: 0.25 = 25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
            ],
            options={
                'verbose_name': 'Break Even Analysis Config',
                'verbose_name_plural': 'Break Even Analysis Configs',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(help_text='Clave API de Keepa', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Configuración activa')),
                ('daily_token_limit', models.PositiveIntegerField(default=5000, help_text='Límite de tokens diarios')),
                ('tokens_used_today', models.PositiveIntegerField(default=0, help_text='Contador de tokens usados hoy')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha del último reset de tokens')),
            ],
            options={
                'verbose_name': 'Keepa Configuration',
                'verbose_name_plural': 'Keepa Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.CharField(default='USD', help_text='Moneda origen', max_length=3)),
                ('to_currency', models.CharField(default='MXN', help_text='Moneda destino', max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tasa de cambio', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('is_active', models.BooleanField(default=True, help_text='Si es la tasa activa')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', help_text='Origen del tipo de cambio', max_length=20)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'is_active'], name='pricing_ana_from_cu_776303_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeepaAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(help_text='Endpoint llamado', max_length=255)),
                ('request_params', models.JSONField(default=dict, help_text='Parámetros de la request')),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP status code de la respuesta', null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Data de la respuesta')),
                ('tokens_consumed', models.PositiveIntegerField(default=0, help_text='Tokens consumidos en esta llamada')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si hubo problema')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Tiempo de ejecución en milisegundos')),
            ],
            options={
                'verbose_name': 'Keepa API Log',
                'verbose_name_plural': 'Keepa API Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='pricing_ana_created_996274_idx'), models.Index(fields=['response_status'], name='pricing_ana_respons_624196_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeepaProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asin', models.CharField(db_index=True, help_text='ASIN del producto', max_length=20)),
                ('marketplace', models.CharField(choices=[('US', 'Amazon USA'), ('MX', 'Amazon MX')], help_text='Marketplace de Amazon', max_length=2)),
                ('current_amazon_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual de Amazon', max_digits=12, null=True)),
                ('buy_box_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de Buy Box (prioritario para USA)', max_digits=12, null=True)),
                ('current_new_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual nuevo', max_digits=12, null=True)),
                ('avg_30_days_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promedio 30 días', max_digits=12, null=True)),
                ('avg_90_days_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promedio 90 días', max_digits=12, null=True)),
                ('title', models.CharField(blank=True, help_text='Título del producto', max_length=500)),
                ('brand', models.CharField(blank=True, help_text='Marca', max_length=255)),
                ('product_category', models.CharField(blank=True, help_text='Categoría del producto', max_length=255)),
                ('sales_rank', models.PositiveIntegerField(blank=True, help_text='Sales rank en su categoría', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Si el producto está disponible')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de Keepa para debugging')),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Última sincronización exitosa')),
                ('sync_successful', models.BooleanField(default=True, help_text='Si la sincronización fue exitosa')),
                ('sync_error_message', models.TextField(blank=True, help_text='Mensaje de error si hubo problema en sync')),
                ('product', models.ForeignKey(blank=True, help_text='Producto asociado (puede ser null si es temporal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keepa_data', to='products.product')),
            ],
            options={
                'verbose_name': 'Keepa Product Data',
                'verbose_name_plural': 'Keepa Product Data',
                'ordering': ['-last_synced_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asin', models.CharField(db_index=True, help_text='ASIN (redundante para queries rápidas)', max_length=20)),
                ('usa_cost_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('usa_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Precio usado de Keepa (USD)', max_digits=12, null=True)),
                ('usa_cost_source', models.CharField(choices=[('buy_box', 'Buy Box Price'), ('amazon', 'Amazon Price'), ('unavailable', 'Unavailable')], default='unavailable', help_text='Fuente del precio USA', max_length=20)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio usado', max_digits=10, null=True)),
                ('current_mx_amazon_price_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('current_mx_amazon_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Precio actual en Amazon MX', max_digits=12, null=True)),
                ('cost_base_mxn_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('cost_base_mxn', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Cost base después de import + IVA', max_digits=12, null=True)),
                ('vat_retention_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('vat_retention', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Retención de IVA (8% de cost base)', max_digits=12, null=True)),
                ('isr_retention_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('isr_retention', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Retención ISR (2.5% de cost base)', max_digits=12, null=True)),
                ('shipping_cost_used_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('shipping_cost_used', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Costo de envío usado en el cálculo', max_digits=10, null=True)),
                ('break_even_price_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('break_even_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Precio de Break Even calculado', max_digits=12, null=True)),
                ('is_feasible', models.BooleanField(default=False, help_text='Si es viable vender el producto')),
                ('is_available_usa', models.BooleanField(default=False, help_text='Si se puede comprar en Amazon USA')),
                ('recommended_price_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('recommended_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Precio recomendado con margen objetivo', max_digits=12, null=True)),
                ('price_difference_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True)),
                ('price_difference', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='MXN', help_text='Diferencia con precio actual MX', max_digits=12, null=True)),
                ('potential_profit_margin', models.DecimalField(blank=True, decimal_places=4, help_text='Margen potencial de ganancia', max_digits=5, null=True)),
                ('confidence_score', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', help_text='Nivel de confianza del análisis', max_length=10)),
                ('analysis_notes', models.TextField(blank=True, help_text='Notas y recomendaciones del análisis')),
                ('analysis_config', models.ForeignKey(help_text='Configuración utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing_analysis.breakevenanalysisconfig')),
                ('mx_keepa_data', models.ForeignKey(help_text='Datos de Keepa MX', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mx_analyses', to='pricing_analysis.keepaproductdata')),
                ('product', models.ForeignKey(help_text='Producto analizado', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_analyses', to='products.product')),
                ('usa_keepa_data', models.ForeignKey(help_text='Datos de Keepa USA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usa_analyses', to='pricing_analysis.keepaproductdata')),
            ],
            options={
                'verbose_name': 'Pricing Analysis Result',
                'verbose_name_plural': 'Pricing Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingAnalysisBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre del batch', max_length=200)),
                ('asins', models.JSONField(default=list, help_text='Lista de ASINs a analizar')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Estado del batch', max_length=20)),
                ('total_asins', models.PositiveIntegerField(default=0, help_text='Total de ASINs en el batch')),
                ('processed_asins', models.PositiveIntegerField(default=0, help_text='ASINs procesados')),
                ('successful_analyses', models.PositiveIntegerField(default=0, help_text='Análisis exitosos')),
                ('failed_analyses', models.PositiveIntegerField(default=0, help_text='Análisis fallidos')),
                ('unavailable_in_usa_count', models.PositiveIntegerField(default=0, help_text='Productos no disponibles en USA')),
                ('error_log', models.JSONField(blank=True, default=dict, help_text='Log de errores durante el procesamiento')),
                ('started_at', models.DateTimeField(blank=True, help_text='Fecha de inicio del procesamiento', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha de finalización', null=True)),
                ('results', models.ManyToManyField(blank=True, help_text='Resultados del análisis', related_name='batches', to='pricing_analysis.pricinganalysisresult')),
            ],
            options={
                'verbose_name': 'Pricing Analysis Batch',
                'verbose_name_plural': 'Pricing Analysis Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='keepaproductdata',
            index=models.Index(fields=['asin', 'marketplace'], name='pricing_ana_asin_ffce8c_idx'),
        ),
        migrations.AddIndex(
            model_name='keepaproductdata',
            index=models.Index(fields=['sync_successful', '-last_synced_at'], name='pricing_ana_sync_su_86c17b_idx'),
        ),
        migrations.AddConstraint(
            model_name='keepaproductdata',
            constraint=models.UniqueConstraint(fields=('asin', 'marketplace'), name='unique_asin_marketplace'),
        ),
        migrations.AddIndex(
            model_name='pricinganalysisresult',
            index=models.Index(fields=['asin', '-created_at'], name='pricing_ana_asin_af9d85_idx'),
        ),
        migrations.AddIndex(
            model_name='pricinganalysisresult',
            index=models.Index(fields=['is_feasible', '-created_at'], name='pricing_ana_is_feas_6e4f26_idx'),
        ),
        migrations.AddIndex(
            model_name='pricinganalysisresult',
            index=models.Index(fields=['is_available_usa'], name='pricing_ana_is_avai_3d7c08_idx'),
        ),
    ]
