# Generated by Django 5.0.6 on 2026-01-16 03:23

from django.db import migrations
from decimal import Decimal


def create_default_config(apps, schema_editor):
    """Create default Break Even Analysis configuration."""
    BreakEvenAnalysisConfig = apps.get_model('pricing_analysis', 'BreakEvenAnalysisConfig')

    # Check if default config already exists
    if not BreakEvenAnalysisConfig.objects.filter(name='Default Configuration').exists():
        BreakEvenAnalysisConfig.objects.create(
            name='Default Configuration',
            is_active=True,
            import_admin_cost_rate=Decimal('0.2000'),
            iva_tax_rate=Decimal('0.1600'),
            vat_retention_rate=Decimal('0.0800'),
            isr_retention_rate=Decimal('0.0250'),
            marketplace_fee_rate=Decimal('0.1500'),
            fixed_shipping_min=70.00,
            fixed_shipping_min_currency='MXN',
            fixed_shipping_max=100.00,
            fixed_shipping_max_currency='MXN',
            min_profit_margin=Decimal('0.1000'),
            target_profit_margin=Decimal('0.2500'),
        )


def reverse_default_config(apps, schema_editor):
    """Remove default configuration."""
    BreakEvenAnalysisConfig = apps.get_model('pricing_analysis', 'BreakEvenAnalysisConfig')
    BreakEvenAnalysisConfig.objects.filter(name='Default Configuration').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_config, reverse_default_config),
    ]
