# Generated by Django 5.0.6 on 2026-01-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_analysis', '0002_create_default_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keepaconfiguration',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, help_text='Fecha del último reset de tokens'),
        ),
    ]
