# Generated by Django 5.0.6 on 2026-01-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_analysis', '0003_alter_keepaconfiguration_last_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricinganalysisresult',
            name='potential_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Margen potencial de ganancia', max_digits=7, null=True),
        ),
    ]
