# Generated by Django 5.0.6 on 2026-01-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_analysis', '0004_alter_pricinganalysisresult_potential_profit_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la marca', max_length=255, unique=True)),
                ('normalized_name', models.CharField(help_text='Nombre normalizado para matching', max_length=255, unique=True)),
                ('is_allowed', models.BooleanField(default=False, help_text='Si la marca esta permitida para venta')),
            ],
            options={
                'verbose_name': 'Brand Restriction',
                'verbose_name_plural': 'Brand Restrictions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['normalized_name'], name='pricing_ana_normali_a004e7_idx')],
            },
        ),
    ]
