# Generated by Django 5.0.6 on 2024-12-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('prep_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepcenter',
            options={'verbose_name': 'Prep Center', 'verbose_name_plural': 'Prep Centers'},
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
