# Generated by Django 5.0.6 on 2025-02-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('prep_centers', '0002_alter_prepcenter_options_prepcenter_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepcenter',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_centers', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_centers', to='cities_light.country'),
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_centers', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='prepcenter',
            name='sub_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_centers', to='cities_light.subregion'),
        ),
        migrations.AlterField(
            model_name='prepcenter',
            name='address',
            field=models.TextField(),
        ),
    ]
