# Generated by Django 5.0.6 on 2025-06-07 16:40

import django.db.models.deletion
import django.db.models.expressions
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_orders', '0002_alter_purchaseorder_amount_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLogisticCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_cost_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar'), ('WHC', 'Warehouse Currency')], default='USD', editable=False, max_length=3)),
                ('shipping_cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10)),
                ('customs_cost_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar'), ('WHC', 'Warehouse Currency')], default='USD', editable=False, max_length=3)),
                ('customs_cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10)),
                ('other_costs_currency', djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar'), ('WHC', 'Warehouse Currency')], default='USD', editable=False, max_length=3)),
                ('other_costs', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10)),
                ('total_cost', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('shipping_cost'), '+', models.F('customs_cost')), '+', models.F('other_costs')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_cost', to='purchases_orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Logistic Cost',
                'verbose_name_plural': 'Purchase Order Logistic Costs',
            },
        ),
    ]
