# Generated by Django 5.0.6 on 2026-03-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepanotification',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='keepanotification',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
