# Generated by Django 5.0.6 on 2025-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0003_salesorder_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='prep_center_folios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
