# Generated by Django 5.0.6 on 2025-03-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0004_salesorder_prep_center_folios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='prep_center_folios',
        ),
    ]
