# Generated by Django 5.0.6 on 2026-01-24 05:14

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0005_remove_salesorder_prep_center_folios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='unit_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='salesorderdetailshipment',
            name='cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
