# Generated by Django 5.0.6 on 2024-12-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplace',
            options={'ordering': ('-created_at',)},
        ),
    ]
