# Generated by Django 5.0.6 on 2025-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_alter_marketplace_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('woocommerce', 'WooCommerce')], default='amazon', max_length=50),
        ),
    ]
