# Generated by Django 5.0.6 on 2024-06-30 23:21

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BOUGHT', 'Bought'), ('IN_WAREHOUSE', 'In warehouse'), ('DELIVERY_PROCESS', 'Delivery process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('customer_state', models.CharField(max_length=50)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_zip_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BOUGHT', 'Bought'), ('IN_WAREHOUSE', 'In warehouse'), ('DELIVERY_PROCESS', 'Delivery process'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=40)),
                ('link_order', models.URLField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetailCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_cost', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('product_cost'), '*', models.Value(Decimal('0.1499999999999999944488848768742172978818416595458984375'))), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('importation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importation_vat', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('importation_cost'), '*', models.Value(Decimal('0.08250000000000000388578058618804789148271083831787109375'))), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('logistics_cost', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('importation_cost'), '+', models.F('importation_vat')), '*', models.Value(Decimal('0.200000000000000011102230246251565404236316680908203125'))), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('logistics_vat', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('logistics_cost'), '*', models.Value(Decimal('0.1600000000000000033306690738754696212708950042724609375'))), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('customer_shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_cost', to='orders.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetailShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(max_length=50)),
                ('courier', models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('ESTAFETA', 'Estafeta'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DISPATCHED', max_length=40)),
                ('dispatch_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
