# Generated by Django 5.0.6 on 2024-12-21 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'external_id',
                    models.CharField(
                        db_index=True, help_text='ASIN, WooCommerce ID', max_length=50
                    ),
                ),
                ('sku', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('HEALTH AND HOUSEHOLD', 'Health & household'),
                            ('TOYS AND GAMES', 'Toys & Games'),
                        ],
                        default='HEALTH AND HOUSEHOLD',
                        max_length=40,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prices',
                        to='products.product',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
