# Generated by Django 5.0.6 on 2024-06-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (SKU) is a unique code that you can assign to each product in your inventory.', max_length=50)),
                ('product_title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
