# Generated by Django 5.0.6 on 2024-12-23 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Product Price', 'verbose_name_plural': 'Product Prices'},
        ),
    ]
