# Generated by Django 5.0.6 on 2025-02-03 17:34

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_productprice_amount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ('MXN', 'Mexican Peso'),
                    ('USD', 'US Dollar'),
                    ('WHC', 'Warehouse Currency'),
                ],
                default='USD',
                editable=False,
                max_length=3,
            ),
        ),
    ]
