# Generated by Django 5.0.6 on 2025-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productprice_amount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock available'),
        ),
    ]
