# Generated by Django 5.0.6 on 2026-01-16 03:22

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Mexican Peso'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
